// import '@/pages/MainPage';
import '@/components/layout/Layout';
import '@/components/main/MainBanner';
import '@/components/main/MainRecommend';
import '@/components/main/MainVOD';
import '@/components/main/MainTop';
import '@/components/main/MainLiveChannel';
import '@/components/main/MainToriginal';
import '@/components/main/MainBottomBanner';
import '@/components/main/MainEventBanner';
